/*
 * UQU - CS - Operating Systems
 * pr. Abdulbaset Gaddah
 * subject: assignment-01-part-2: shared-memory - part-1-MyServer
 * authors:
 * - MHD Maher Azkoul
 *   438017578
 *   group: 3 - no.: 27
 * - Anas Mohammad Hashem Nowawi
 *   438008655
 *   group: 3 - no.: 25
 * 
 * program description:
 *    This program is one of 2 parts of the whole program
 * the goal of the program is to have a value
 * and let the second part guess the number.
 *    The two parts will communicate via POSIX-shared memory.
 *    This part will scan values and replace each non-true
 * value with -1.
 *    If the right value was founded, then this program will
 * display a message and destroy shared memory, then it
 * will be terminated.
 */

#include <stdio.h>
#include <stdlib.h>
#include <sys/ipc.h> 
#include <sys/shm.h> 
#include <sys/types.h> 
#include <unistd.h>

// size of the array of values
#define SH_SIZE 32

// control keys
#define IS_FOUNDED_KEY 'f'
#define SERVER_KEY 's'
#define CLIENT_KEY 'c'

int main(int argc, char** argv) {

    // specify keys
    key_t key = 's' * 'h';
    key_t signal = 's';

    // build shared memory
    // add 1 for signal register
    int shmid = shmget(key, (SH_SIZE + 1) * sizeof(int), IPC_CREAT | 0666);
    if (shmid < 0) {
        perror("shmget error - server");
        exit(1);
    }

    // attach buffer memory
    int *mem = shmat(shmid, NULL, 0);  
    if (mem == (int *) - 1) {
        perror("shmat error - server");
        exit(1);
    }

    int luckyNumber = 5;

    // initializing the array
    for(int i = 0; i < SH_SIZE; i++) {
        mem[i] = -1;
    }

    // print init values
    printf("Initial status of shared memory.\n");
    for(int i = 0; i < SH_SIZE; i++) {
        printf("%d, ", mem[i]);
    }
    printf("\n");

    // give control to the client
    mem[SH_SIZE] = CLIENT_KEY;
    printf("now the server is listening to the client.\n\n");

    while(1) {
        if(mem[SH_SIZE] == SERVER_KEY) {
            // read numbers genrated by client
            printf("Numbers generated by the client and read by the server.\n");
            for(int i = 0; i < SH_SIZE; i++) {
                printf("%d, ", mem[i]);
            }
            printf("\n\n");

            // replace values to -1 exept lucky number
            for(int i = 0; i < SH_SIZE; i++) {
                if(mem[i] != luckyNumber) {
                    mem[i] = -1;
                }
            }

            // print values after replacing
            printf("after replacing values other then lucky number to -1.\n");
            for(int i = 0; i < SH_SIZE; i++) {
                printf("%d, ", mem[i]);
            }
            printf("\n\n");

            // give control to the client
            mem[SH_SIZE] = CLIENT_KEY;

        // if control with client
        } else if(mem[SH_SIZE] == CLIENT_KEY) {
            sleep(1);

        // if recieved founded signal
        } else if(mem[SH_SIZE] == IS_FOUNDED_KEY) {
            printf("The lucky number [%d] is found –the server will be terminated soon.\n\n", luckyNumber);
            break;
        }
    }

    //detach from shared memory 
    shmdt(mem);

    // destroy the shared memory 
    shmctl(shmid, IPC_RMID, NULL);

    printf("the server says goodbye!\n\n");
    
    return (EXIT_SUCCESS);
}
